# Generated by Django 5.2.9 on 2025-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_quoted_amount_assignment_writer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignments/attachments/'),
        ),
    ]
