# Generated by Django 5.2.9 on 2025-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='revision_count',
            field=models.IntegerField(default=0),
        ),
    ]
