# Generated by Django 5.2.9 on 2025-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10),
        ),
    ]
